### PR TITLE
Clear the wishlist's ids from local storage when logout

### PR DESCRIPTION
**Pull request by vitoriaHeliane**
#### What is the purpose of this pull request?
As the title says.

#### How should this be manually tested?
[Click here to access the workspace.](https://vitoria--storecomponents.myvtex.com/)

#### Types of changes
- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by rnbez** [comment]
Shouldn't this be something handled by the Wishlist app?

**Comment by vitoriaHeliane** [comment]
> Shouldn't this be something handled by the Wishlist app?

Because it is something that should be done when the logout option is  selected, but there is no way to the wishlist app know when it happens, so this is the way I thought to resolve it.

**Comment by rnbez** [comment]
>Shouldn't this be something handled by the Wishlist app?
I mean, the responsibility of removing something from local storage should not belong to the login app. The login app should be responsible for the login, and only the login.

>Because it is something that should be done when the logout option is selected, but there is no way to the wishlist app know when it happens, so this is the way I thought to resolve it.
@vitoriaHeliane  Then we should consider triggering a window event when the logout happens.

cc @klzns @felippenardi @brunojdo

**Comment by brunojdo** [comment]
I agree with @rnbez This isn't the responsibility of the login app.

**Pull request closed without merging**
